services:
  postgres:
    image: postgres:16
    container_name: reservation-lab-postgres
    environment:
        POSTGRES_DB: reservation_lab
        POSTGRES_USER: reservation_lab_user
        POSTGRES_PASSWORD: reservation_lab_password
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: reservation-lab-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
volumes:
  postgres_data:
