spring:
  application:
    name: reservation-lab

  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: guest
      password: guest

  datasource:
    url: jdbc:postgresql://localhost:5432/reservation_lab
    username: reservation_lab_user
    password: reservation_lab_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

  threads:
    virtual:
      enabled: true

server:
  port: 8080

app:
  messaging:
    queues:
      event-created: event.created.queue